horizontal position is added, vertical is redone with another parent
NanoCraftGame/nanocraft pull request #31
Opened 2024-04-12 08:59 UTC by Erball-M

![Снимок экрана 2024-04-12 145841](https://github.com/NanoCraftGame/nanocraft/assets/119080597/7894c81d-0e61-429c-8d03-17d6f4766a8c)
![Снимок экрана 2024-04-12 145920](https://github.com/NanoCraftGame/nanocraft/assets/119080597/7fa4be5f-e921-4f4e-859d-854641cbd5bb)

2024-04-15 09:12 UTC, RB-Lab requested changes
Good start, but I don't like the positions. Should be like this:
<img width="421" alt="image" src="https://github.com/NanoCraftGame/nanocraft/assets/5694678/86733d73-c876-49b0-8c7c-8407389f94c4">

2024-04-15 09:12 UTC, RB-Lab commented on src/lib/components/DropDown.svelte
> -	}
Nah, this is a bad idea. Try scrolling with open dropdown.

2024-04-15 09:12 UTC, RB-Lab commented on src/lib/components/DropDown.svelte
> +			dropdownDiv.style.left = `${left}px`
Okay, at this point, I guess it's time to use [popper.js](https://popper.js.org/docs/v2/)

2024-04-17 08:22 UTC, Erball-M commented
this branch was merged to EM/taskDescription ( PR #24 )

2024-04-18 07:40 UTC, RB-Lab approved these changes

2024-04-18 10:41 UTC, merged